# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_total', models.CharField(default='unknown', max_length=20)),
                ('swap_total', models.CharField(default='unknown', max_length=20)),
                ('cpu_type', models.CharField(default='unknown', max_length=20)),
                ('cpu_total', models.IntegerField(default=0)),
                ('os_type', models.CharField(default='unknown', max_length=20)),
                ('disk_total', models.CharField(default='unknown', max_length=20)),
                ('disk_mount', models.CharField(default='unknown', max_length=20)),
                ('server_type', models.CharField(default='unknown', max_length=20)),
                ('host_name', models.CharField(default='unknown', max_length=20)),
                ('os_kernel', models.CharField(default='unknown', max_length=20)),
                ('ipv4', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMachine',
            fields=[
                ('physicalIp', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('machineRoom_address', models.CharField(max_length=8)),
                ('machineRoom_attr', models.CharField(max_length=10)),
                ('machine_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myhost.Machine_info')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('virtualIp', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('process_info', models.TextField(max_length=10240)),
                ('note', models.TextField(max_length=10240)),
                ('physicalMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhost.PhysicalMachine')),
            ],
        ),
    ]
