# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhost', '0002_auto_20171116_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physicalIp', models.CharField(max_length=16)),
                ('machineRoom_address', models.CharField(max_length=8)),
                ('machineRoom_attr', models.CharField(max_length=10)),
                ('machine_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myhost.Machine_info')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtualIp', models.CharField(max_length=16)),
                ('process_info', models.TextField(max_length=10240)),
                ('note', models.TextField(max_length=10240)),
                ('physicalMachine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myhost.PhysicalMachine')),
            ],
        ),
    ]
