# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0005_auto_20171113_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.IntegerField(default=0, verbose_name='user')),
            ],
        ),
    ]
