# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myManager', '0006_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='me',
        ),
    ]
